### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by britsanto** [minimod-nutrition/minimod-website#22]
Hi Aleks, I just had a look at the website and noticed that none of the added pictures can be seen on the homepage.
Did I forget to include something?

**Comment by amichuda** [comment]
Good question! From what I can see, the pictures you're linking to aren't actually in the `pictures` folder. Can you check that on your end?

**Comment by britsanto** [comment]
Oh my gosh, I could've sworn I added it. I guess I forgot to save it!
